language: cpp
cache:
  ccache: true

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode12
      compiler: clang
    - os: osx
      osx_image: xcode12
      compiler: gcc

env:
- METHOD=FetchContent
- METHOD=ExternalProject
- METHOD=LocalInstall

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
