language: cpp

os:
- linux
- osx

compiler:
- clang
- gcc

env:
- METHOD=FetchContent
- METHOD=ExternalProject
- METHOD=LocalInstall

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
